package aproc.map;
// Generated Mar 22, 2016 5:19:24 PM by Hibernate Tools 3.6.0


import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Uztproc generated by hbm2java
 */
public class Uztproc  implements java.io.Serializable {


     private UztprocId id;
     private Uztproc uztproc;
     private Uztsist uztsist;
     private String uztprocNombre;
     private Clob uztprocEjecucion;
     private Clob uztprocInicio;
     private Clob uztprocSalida;
     private Character uztprocEstado;
     private Date uztprocFecha;
     private Clob uztprocDescripcion;
     private Set uztprocs = new HashSet(0);

    public Uztproc() {
    }

	
    public Uztproc(UztprocId id, Uztsist uztsist) {
        this.id = id;
        this.uztsist = uztsist;
    }
    public Uztproc(UztprocId id, Uztproc uztproc, Uztsist uztsist, String uztprocNombre, Clob uztprocEjecucion, Clob uztprocInicio, Clob uztprocSalida, Character uztprocEstado, Date uztprocFecha, Clob uztprocDescripcion, Set uztprocs) {
       this.id = id;
       this.uztproc = uztproc;
       this.uztsist = uztsist;
       this.uztprocNombre = uztprocNombre;
       this.uztprocEjecucion = uztprocEjecucion;
       this.uztprocInicio = uztprocInicio;
       this.uztprocSalida = uztprocSalida;
       this.uztprocEstado = uztprocEstado;
       this.uztprocFecha = uztprocFecha;
       this.uztprocDescripcion = uztprocDescripcion;
       this.uztprocs = uztprocs;
    }
   
    public UztprocId getId() {
        return this.id;
    }
    
    public void setId(UztprocId id) {
        this.id = id;
    }
    public Uztproc getUztproc() {
        return this.uztproc;
    }
    
    public void setUztproc(Uztproc uztproc) {
        this.uztproc = uztproc;
    }
    public Uztsist getUztsist() {
        return this.uztsist;
    }
    
    public void setUztsist(Uztsist uztsist) {
        this.uztsist = uztsist;
    }
    public String getUztprocNombre() {
        return this.uztprocNombre;
    }
    
    public void setUztprocNombre(String uztprocNombre) {
        this.uztprocNombre = uztprocNombre;
    }
    public Clob getUztprocEjecucion() {
        return this.uztprocEjecucion;
    }
    
    public void setUztprocEjecucion(Clob uztprocEjecucion) {
        this.uztprocEjecucion = uztprocEjecucion;
    }
    public Clob getUztprocInicio() {
        return this.uztprocInicio;
    }
    
    public void setUztprocInicio(Clob uztprocInicio) {
        this.uztprocInicio = uztprocInicio;
    }
    public Clob getUztprocSalida() {
        return this.uztprocSalida;
    }
    
    public void setUztprocSalida(Clob uztprocSalida) {
        this.uztprocSalida = uztprocSalida;
    }
    public Character getUztprocEstado() {
        return this.uztprocEstado;
    }
    
    public void setUztprocEstado(Character uztprocEstado) {
        this.uztprocEstado = uztprocEstado;
    }
    public Date getUztprocFecha() {
        return this.uztprocFecha;
    }
    
    public void setUztprocFecha(Date uztprocFecha) {
        this.uztprocFecha = uztprocFecha;
    }
    public Clob getUztprocDescripcion() {
        return this.uztprocDescripcion;
    }
    
    public void setUztprocDescripcion(Clob uztprocDescripcion) {
        this.uztprocDescripcion = uztprocDescripcion;
    }
    public Set getUztprocs() {
        return this.uztprocs;
    }
    
    public void setUztprocs(Set uztprocs) {
        this.uztprocs = uztprocs;
    }




}


