package aproc.map;
// Generated Mar 22, 2016 5:19:24 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * UztprocId generated by hbm2java
 */
public class UztprocId  implements java.io.Serializable {


     private BigDecimal uztsistId;
     private BigDecimal uztprocId;

    public UztprocId() {
    }

    public UztprocId(BigDecimal uztsistId, BigDecimal uztprocId) {
       this.uztsistId = uztsistId;
       this.uztprocId = uztprocId;
    }
   
    public BigDecimal getUztsistId() {
        return this.uztsistId;
    }
    
    public void setUztsistId(BigDecimal uztsistId) {
        this.uztsistId = uztsistId;
    }
    public BigDecimal getUztprocId() {
        return this.uztprocId;
    }
    
    public void setUztprocId(BigDecimal uztprocId) {
        this.uztprocId = uztprocId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UztprocId) ) return false;
		 UztprocId castOther = ( UztprocId ) other; 
         
		 return ( (this.getUztsistId()==castOther.getUztsistId()) || ( this.getUztsistId()!=null && castOther.getUztsistId()!=null && this.getUztsistId().equals(castOther.getUztsistId()) ) )
 && ( (this.getUztprocId()==castOther.getUztprocId()) || ( this.getUztprocId()!=null && castOther.getUztprocId()!=null && this.getUztprocId().equals(castOther.getUztprocId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUztsistId() == null ? 0 : this.getUztsistId().hashCode() );
         result = 37 * result + ( getUztprocId() == null ? 0 : this.getUztprocId().hashCode() );
         return result;
   }   


}


