package aproc.map;
// Generated Mar 22, 2016 5:19:24 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Uztrol generated by hbm2java
 */
public class Uztrol  implements java.io.Serializable {


     private BigDecimal uztrolId;
     private String uztrolNombre;
     private Character uztrolEstado;
     private Date uztrolFecha;
     private Set uztrouses = new HashSet(0);

    public Uztrol() {
    }

	
    public Uztrol(BigDecimal uztrolId) {
        this.uztrolId = uztrolId;
    }
    public Uztrol(BigDecimal uztrolId, String uztrolNombre, Character uztrolEstado, Date uztrolFecha, Set uztrouses) {
       this.uztrolId = uztrolId;
       this.uztrolNombre = uztrolNombre;
       this.uztrolEstado = uztrolEstado;
       this.uztrolFecha = uztrolFecha;
       this.uztrouses = uztrouses;
    }
   
    public BigDecimal getUztrolId() {
        return this.uztrolId;
    }
    
    public void setUztrolId(BigDecimal uztrolId) {
        this.uztrolId = uztrolId;
    }
    public String getUztrolNombre() {
        return this.uztrolNombre;
    }
    
    public void setUztrolNombre(String uztrolNombre) {
        this.uztrolNombre = uztrolNombre;
    }
    public Character getUztrolEstado() {
        return this.uztrolEstado;
    }
    
    public void setUztrolEstado(Character uztrolEstado) {
        this.uztrolEstado = uztrolEstado;
    }
    public Date getUztrolFecha() {
        return this.uztrolFecha;
    }
    
    public void setUztrolFecha(Date uztrolFecha) {
        this.uztrolFecha = uztrolFecha;
    }
    public Set getUztrouses() {
        return this.uztrouses;
    }
    
    public void setUztrouses(Set uztrouses) {
        this.uztrouses = uztrouses;
    }




}


