package aproc.map;
// Generated Mar 22, 2016 5:19:24 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * UztrousId generated by hbm2java
 */
public class UztrousId  implements java.io.Serializable {


     private BigDecimal uztrolId;
     private BigDecimal uztuserPidm;

    public UztrousId() {
    }

    public UztrousId(BigDecimal uztrolId, BigDecimal uztuserPidm) {
       this.uztrolId = uztrolId;
       this.uztuserPidm = uztuserPidm;
    }
   
    public BigDecimal getUztrolId() {
        return this.uztrolId;
    }
    
    public void setUztrolId(BigDecimal uztrolId) {
        this.uztrolId = uztrolId;
    }
    public BigDecimal getUztuserPidm() {
        return this.uztuserPidm;
    }
    
    public void setUztuserPidm(BigDecimal uztuserPidm) {
        this.uztuserPidm = uztuserPidm;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UztrousId) ) return false;
		 UztrousId castOther = ( UztrousId ) other; 
         
		 return ( (this.getUztrolId()==castOther.getUztrolId()) || ( this.getUztrolId()!=null && castOther.getUztrolId()!=null && this.getUztrolId().equals(castOther.getUztrolId()) ) )
 && ( (this.getUztuserPidm()==castOther.getUztuserPidm()) || ( this.getUztuserPidm()!=null && castOther.getUztuserPidm()!=null && this.getUztuserPidm().equals(castOther.getUztuserPidm()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUztrolId() == null ? 0 : this.getUztrolId().hashCode() );
         result = 37 * result + ( getUztuserPidm() == null ? 0 : this.getUztuserPidm().hashCode() );
         return result;
   }   


}


