package aproc.map;
// Generated Mar 22, 2016 5:19:24 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Uztrous generated by hbm2java
 */
public class Uztrous  implements java.io.Serializable {


     private UztrousId id;
     private Uztuser uztuser;
     private Uztrol uztrol;
     private Date uztrousFcha;
     private Character uztrousEstado;

    public Uztrous() {
    }

	
    public Uztrous(UztrousId id, Uztuser uztuser, Uztrol uztrol) {
        this.id = id;
        this.uztuser = uztuser;
        this.uztrol = uztrol;
    }
    public Uztrous(UztrousId id, Uztuser uztuser, Uztrol uztrol, Date uztrousFcha, Character uztrousEstado) {
       this.id = id;
       this.uztuser = uztuser;
       this.uztrol = uztrol;
       this.uztrousFcha = uztrousFcha;
       this.uztrousEstado = uztrousEstado;
    }
   
    public UztrousId getId() {
        return this.id;
    }
    
    public void setId(UztrousId id) {
        this.id = id;
    }
    public Uztuser getUztuser() {
        return this.uztuser;
    }
    
    public void setUztuser(Uztuser uztuser) {
        this.uztuser = uztuser;
    }
    public Uztrol getUztrol() {
        return this.uztrol;
    }
    
    public void setUztrol(Uztrol uztrol) {
        this.uztrol = uztrol;
    }
    public Date getUztrousFcha() {
        return this.uztrousFcha;
    }
    
    public void setUztrousFcha(Date uztrousFcha) {
        this.uztrousFcha = uztrousFcha;
    }
    public Character getUztrousEstado() {
        return this.uztrousEstado;
    }
    
    public void setUztrousEstado(Character uztrousEstado) {
        this.uztrousEstado = uztrousEstado;
    }




}


