package aproc.map;
// Generated Mar 22, 2016 5:19:24 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Uztsist generated by hbm2java
 */
public class Uztsist  implements java.io.Serializable {


     private BigDecimal uztsistId;
     private String uztsistNombre;
     private Clob uztsistDescripcion;
     private Clob uztsistRuta;
     private Character uztsistEstado;
     private Date uztsistFecha;
     private Set uztprocs = new HashSet(0);

    public Uztsist() {
    }

	
    public Uztsist(BigDecimal uztsistId) {
        this.uztsistId = uztsistId;
    }
    public Uztsist(BigDecimal uztsistId, String uztsistNombre, Clob uztsistDescripcion, Clob uztsistRuta, Character uztsistEstado, Date uztsistFecha, Set uztprocs) {
       this.uztsistId = uztsistId;
       this.uztsistNombre = uztsistNombre;
       this.uztsistDescripcion = uztsistDescripcion;
       this.uztsistRuta = uztsistRuta;
       this.uztsistEstado = uztsistEstado;
       this.uztsistFecha = uztsistFecha;
       this.uztprocs = uztprocs;
    }
   
    public BigDecimal getUztsistId() {
        return this.uztsistId;
    }
    
    public void setUztsistId(BigDecimal uztsistId) {
        this.uztsistId = uztsistId;
    }
    public String getUztsistNombre() {
        return this.uztsistNombre;
    }
    
    public void setUztsistNombre(String uztsistNombre) {
        this.uztsistNombre = uztsistNombre;
    }
    public Clob getUztsistDescripcion() {
        return this.uztsistDescripcion;
    }
    
    public void setUztsistDescripcion(Clob uztsistDescripcion) {
        this.uztsistDescripcion = uztsistDescripcion;
    }
    public Clob getUztsistRuta() {
        return this.uztsistRuta;
    }
    
    public void setUztsistRuta(Clob uztsistRuta) {
        this.uztsistRuta = uztsistRuta;
    }
    public Character getUztsistEstado() {
        return this.uztsistEstado;
    }
    
    public void setUztsistEstado(Character uztsistEstado) {
        this.uztsistEstado = uztsistEstado;
    }
    public Date getUztsistFecha() {
        return this.uztsistFecha;
    }
    
    public void setUztsistFecha(Date uztsistFecha) {
        this.uztsistFecha = uztsistFecha;
    }
    public Set getUztprocs() {
        return this.uztprocs;
    }
    
    public void setUztprocs(Set uztprocs) {
        this.uztprocs = uztprocs;
    }




}


