package aproc.map;
// Generated Mar 22, 2016 5:19:24 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Uztuser generated by hbm2java
 */
public class Uztuser  implements java.io.Serializable {


     private BigDecimal uztuserPidm;
     private String uztuserId;
     private String uztuserNombres;
     private String uztuserCargo;
     private Character uztuserEstado;
     private String uztuserCampus;
     private Set uztrouses = new HashSet(0);

    public Uztuser() {
    }

	
    public Uztuser(BigDecimal uztuserPidm) {
        this.uztuserPidm = uztuserPidm;
    }
    public Uztuser(BigDecimal uztuserPidm, String uztuserId, String uztuserNombres, String uztuserCargo, Character uztuserEstado, String uztuserCampus, Set uztrouses) {
       this.uztuserPidm = uztuserPidm;
       this.uztuserId = uztuserId;
       this.uztuserNombres = uztuserNombres;
       this.uztuserCargo = uztuserCargo;
       this.uztuserEstado = uztuserEstado;
       this.uztuserCampus = uztuserCampus;
       this.uztrouses = uztrouses;
    }
   
    public BigDecimal getUztuserPidm() {
        return this.uztuserPidm;
    }
    
    public void setUztuserPidm(BigDecimal uztuserPidm) {
        this.uztuserPidm = uztuserPidm;
    }
    public String getUztuserId() {
        return this.uztuserId;
    }
    
    public void setUztuserId(String uztuserId) {
        this.uztuserId = uztuserId;
    }
    public String getUztuserNombres() {
        return this.uztuserNombres;
    }
    
    public void setUztuserNombres(String uztuserNombres) {
        this.uztuserNombres = uztuserNombres;
    }
    public String getUztuserCargo() {
        return this.uztuserCargo;
    }
    
    public void setUztuserCargo(String uztuserCargo) {
        this.uztuserCargo = uztuserCargo;
    }
    public Character getUztuserEstado() {
        return this.uztuserEstado;
    }
    
    public void setUztuserEstado(Character uztuserEstado) {
        this.uztuserEstado = uztuserEstado;
    }
    public String getUztuserCampus() {
        return this.uztuserCampus;
    }
    
    public void setUztuserCampus(String uztuserCampus) {
        this.uztuserCampus = uztuserCampus;
    }
    public Set getUztrouses() {
        return this.uztrouses;
    }
    
    public void setUztrouses(Set uztrouses) {
        this.uztrouses = uztrouses;
    }




}


